<?php
function survey_permissions(){
	return array(
		"administer survey"=>array(
			"title"=>"Administer survey configuration",
			"description"=>"Modify survey module configuration"
		),
		"create survey"=>array(
			"title"=>"Create/modify survey",
			"description"=>"create/modify surveys"
		)
	);
}

function survey_menu(){
	return array(
		"admin/config/survey"=>array(
			"title"=>"Survey Admin",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_admin_form"),
			"access arguments"=>array("administer survey"),
			"file"=>"survey.admin.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/list"=>array(
			"title"=>"List of surveys",
			"page callback"=>"survey_list",
			"access arguments"=>array("access content"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/add"=>array(
			"title"=>"Add Survey",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_edit_form",1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey"=>array(
			"title callback"=>"survey_callback_title",
			"title arguments"=>array(1),
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_form",1),
			"access arguments"=>array("view survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"survey/%survey/edit"=>array(
			"title"=>"Edit",
			"page arguments"=>"drupal_get_form",
			"page arguments"=>array("survey_edit_form",1),
			"access arguments"=>"create survey",
			"file"=>"survey.pages.inc",
			"type"=>MENU_LOCAL_TASK
		),
		"survey/%survey/page/list"=>array(
			"title callback"=>"survey_pages_title_callback",
			"title arguments"=>array(1),
			"page callback"=>"survey_pages_list",
			"page arguments"=>array(1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/page/add"=>array(
			"title"=>"Add survey page",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_page_form"),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/page/%survey_page"=>array(
			"title callback"=>"survey_page_title_callback",
			"title arguments"=>array(1,3),
			"page callback"=>"survey_page_view",
			"page arguments"=>array(1,3),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/page/%survey_page/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"survey/%survey/page/%survey_page/edit"=>array(
			"title"=>"Edit",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_page_form",1,3),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_LOCAL_TASK
		),
		"survey/%survey/question/list"=>array(
			"title callback"=>"survey_questions_title_callback",
			"title arguments"=>array(1),
			"page callback"=>"survey_questions_list",
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/question/add"=>array(
			"title"=>"Add survey question",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_question_form",1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/question/%survey_question"=>array(
			"title callback"=>"survey_question_title_callback",
			"title arguments"=>array(1,3),
			"page callback"=>"survey_question_view",
			"page arguments"=>array(1,3),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/question/%survey_question/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"survey/%survey/question/%survey_question/edit"=>array(
			"title"=>"Edit",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_question_form",1,3),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_LOCAL_TASK
		)
	);
}

function survey_load($survey_id, $reset=false){
	
}

function survey_load_multiple(){
	
}

function survey_callback_title($survey, $reset=false){
	
}

function survey_question_load($question_id, $reset=false){
	
}

function survey_question_load_multiple(){
	
}

function survey_get_questions($survey_id){
	
}