<?php

define("QTYPE_TEXT",1);
define("QTYPE_YES_NO",2);
define("QTYPE_TRUE_FALSE",3);
define("QTYPE_SELECT_SINGLE",4);
define("QTYPE_SELECT_MULTI",5);

function survey_permissions(){
	return array(
		"administer survey"=>array(
			"title"=>"Administer survey configuration",
			"description"=>"Modify survey module configuration"
		),
		"create survey"=>array(
			"title"=>"Create/modify survey",
			"description"=>"create/modify surveys"
		)
	);
}

function survey_menu(){
	return array(
		"admin/config/survey"=>array(
			"title"=>"Survey Admin",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_admin_form"),
			"access arguments"=>array("administer survey"),
			"file"=>"survey.admin.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/list"=>array(
			"title"=>"List of surveys",
			"page callback"=>"survey_list",
			"access arguments"=>array("access content"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/add"=>array(
			"title"=>"Add Survey",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_edit_form"),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey"=>array(
			"title callback"=>"survey_callback_title",
			"title arguments"=>array(1),
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_form",1),
			"access arguments"=>array("view survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"survey/%survey/edit"=>array(
			"title"=>"Edit",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_edit_form",1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_LOCAL_TASK
		),
		"survey/%survey/page/list"=>array(
			"title callback"=>"survey_pages_title_callback",
			"title arguments"=>array(1),
			"page callback"=>"survey_pages_list",
			"page arguments"=>array(1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/page/add"=>array(
			"title"=>"Add survey page",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_page_form",1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/page/%survey_page"=>array(
			"title callback"=>"survey_page_title_callback",
			"title arguments"=>array(1,3),
			"page callback"=>"survey_page_view",
			"page arguments"=>array(1,3),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/page/%survey_page/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"survey/%survey/page/%survey_page/edit"=>array(
			"title"=>"Edit",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_page_form",1,3),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_LOCAL_TASK
		),
		"survey/%survey/question/list"=>array(
			"title callback"=>"survey_questions_title_callback",
			"title arguments"=>array(1),
			"page callback"=>"survey_questions_list",
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/question/add"=>array(
			"title"=>"Add survey question",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_question_form",1),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/question/%survey_question"=>array(
			"title callback"=>"survey_question_title_callback",
			"title arguments"=>array(1,3),
			"page callback"=>"survey_question_view",
			"page arguments"=>array(1,3),
			"file"=>"survey.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"survey/%survey/question/%survey_question/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"survey/%survey/question/%survey_question/edit"=>array(
			"title"=>"Edit",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("survey_question_form",1,3),
			"access arguments"=>array("create survey"),
			"file"=>"survey.pages.inc",
			"type"=>MENU_LOCAL_TASK
		)
	);
}

function survey_load($survey_id, $reset=false){
	
	$surveys = survey_load_multiple(array($survey_id), $reset);
	return reset($surveys);
	
}

function survey_load_multiple($survey_ids = array(), $conditions = array(), $reset = false){
	
	return entity_load("survey", $survey_ids, $conditions, $reset);
	
}

function survey_callback_title($survey){
	
	
	
}

function survey_question_load($question_id, $reset=false){
	
	$questions = survey_question_load_multiple(array($question_id), $reset);
	return reset($questions);
	
}

function survey_question_load_multiple($question_ids = array(), $conditions = array(), $reset = false){
	
	return entity_load($question_ids, $conditions, $reset);
	
}

function survey_theme($existing, $type, $theme, $path){
	
	return array(
		"survey_list"=>array(
			"variables"=>array(
				"surveys"=>null
			),
			"template"=>"templates/survey-list"
		)
	);
	
}

function survey_entity_info(){
	
	return array(
		"survey"=>array(
			"label"=>"Survey",
			"controller class"=>"SurveyEntityController",
			"base table"=>"surveys",
			"load hook"=>"survey_load",
			"fieldable"=>true,
			"entity keys"=>array(
				"id"=>"id"
			),
			"bundles"=>array(
				"survey"=>array(
					"label"=>t("Survey"),
					"admin"=>array(
						"path"=>"admin/config/survey",
						"access arguments"=>array("administer survey")
					)
				)
			)
		),
		"survey_question"=>array(
			"label"=>"Survey Question",
			"controller class"=>"SurveyQuestionEntityController",
			"base table"=>"survey_questions",
			"load hook"=>"survey_question_load",
			"fieldable"=>true,
			"entity_keys"=>array(
				"id"=>"id"
			),
			"bundles"=>array(
				"survey_question"=>array(
					"label"=>t("Survey Questions"),
					"admin"=>array(
						"path"=>"admin/config/survey",
						"access arguments"=>array("administer survey")
					)
				)
			)
		)
	);
	
}

function survey_field_extra_fields(){
	
	return array(
		"survey"=>array(
			"survey"=>array(
				"form"=>array(
					"title"=>array(
						"name"=>t("Title"),
						"description"=>t("Survey title"),
						"weight"=>1
					),
					"description"=>array(
						"name"=>t("Description"),
						"description"=>t("Survey description"),
						"weight"=>2
					)
				),
				"display"=>array(
					"title"=>array(
						"name"=>t("Title"),
						"description"=>t("Survey title"),
						"weight"=>1
					),
					"description"=>array(
						"name"=>t("Description"),
						"description"=>t("Survey description"),
						"weight"=>2
					)
				)
			)
		)
	);
	
}

function survey_get_all(){
	
}

function survey_add($title, $desc){
	
	return SurveyDb::survey_add($title, $desc);
	
}

function survey_page_get_all($survey_id){
	
	return SurveyDb::survey_page_get_all($survey_id);
	
}

function survey_page_add($survey_id, $title, $weight){
	
	return SurveyDb::survey_page_add($survey_id, $title, $weight);
	
}

function survey_get_questions($survey_id){
	
}