<?php
function erp_account_install(){
	
	try {
		AccountDb::modify_tables();
		
		drupal_set_message(t("Successfully modified ERP Account tables"));
	}catch(Exception $e){
		watchdog_exception("erp_account", $e);
		
		drupal_set_message(t("Unable to modify ERP Account tables"),"error");
	}
	
}

function erp_account_uninstall(){
	
}

function erp_account_permission(){
	
	return array(
		"administer erp accounts"=>array(
			"title"=>"Administer ERP Accounts",
			"description"=>"Administer erp accounts"
		)
	);
	
}

function erp_account_load($account_id, $reset = false){
	
	$accounts = erp_account_load_multiple($account_id, $reset);
	return reset($accounts);
	
}

function erp_account_load_multiple($account_ids = array(), $conditions = array(), $reset = false){

	return entity_load("erp_account", $account_ids, $conditions, $reset);
	
}

function erp_account_menu(){
	
	return array(
		"admin/config/erp/accounts"=>array(
			"title"=>"ERP Accounts",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_account_accounts_config_form"),
			"access arguments"=>array("administer erp accounts"),
			"file"=>"erp_account.admin.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"erp/client/%erp_client/account/list"=>array(
			"title"=>"ERP Accounts List",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_account_list_form", 2),
			"access arguments"=>array("administer erp accounts"),
			"file"=>"erp_account.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"erp/client/%erp_client/account/add"=>array(
			"title"=>"Add ERP Account",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_account_form", 2),
			"access arguments"=>array("administer erp accounts"),
			"file"=>"erp_account.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"erp/client/%erp_client/account/%erp_account"=>array(
			"title"=>"ERP Account",
			"page callback"=>"erp_account_view",
			"page arguments"=>array(2, 4),
			"access arguments"=>array("administer erp accounts"),
			"file"=>"erp_account.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"erp/client/%erp_client/account/%erp_account/view"=>array(
			"title"=>"View ERP Account",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"erp/client/%erp_client/account/%erp_account/edit"=>array(
			"title"=>"Edit ERP Account",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_account_form", 2, 4),
			"access arguments"=>array("administer erp accounts"),
			"file"=>"erp_account.pages.inc",
			"type"=>MENU_LOCAL_TASK
		)
	);
	
}

function erp_account_entity_info(){
	
	return array(
		"erp_account"=>array(
			"label"=>"ERP Account",
			"label callback"=>"erp_account_label",
// 			"controller class"=>"AccountController"
			"base table"=>"erp_accounts",
			"load hook"=>"erp_account_load",
			"uri_callback"=>"erp_account_uri",
			"fieldable"=>true,
			"entity keys"=>array(
				"id"=>"id"
			),
			"bundles"=>array(
				"erp_account"=>array(
					"label"=>t("ERP Account"),
					"admin"=>array(
						"path"=>"admin/config/erp/account",
						"access arguments"=>array("administer erp accounts")
					)
				)
			)
		)
	);
	
}

function erp_account_field_extra_fields(){
	
	return array(
		"erp_account"=>array(
			"erp_account"=>array(
				"form"=>array(
					"name"=>array(
						"label"=>t("Name"),
						"description"=>t("Account name"),
						"weight"=>1
					),
					"description"=>array(
						"label"=>t("Description"),
						"description"=>t("Account description"),
						"weight"=>2
					),
					"code"=>array(
						"label"=>t("Code"),
						"description"=>t("Account code"),
						"weight"=>3
					)
				),
				"display"=>array(
					"name"=>array(
						"label"=>t("Name"),
						"description"=>t("Account name"),
						"weight"=>1
					),
					"description"=>array(
						"label"=>t("Description"),
						"description"=>t("Account description"),
						"weight"=>2
					),
					"code"=>array(
						"label"=>t("Code"),
						"description"=>t("Account code"),
						"weight"=>3
					)					
				)
			)
		)
	);
	
}