<?php

function erp_client_install(){
	
// 	$db = new ClientDb();
// 	try {
// 		$db->modify_tables();
// 	}
// 	catch(Exception $e){
// 		watchdog_exception("ClientDB", $e);
// 	}
	
}

function erp_client_uninstall(){
	
}

/**
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 */
function erp_client_permission(){
	
	return array(
		"administer clients"=>array(
			"title"=>t("Administer ERP Client"),
			"description"=>t("Administer erp clients")
		)
	);
	
}

/**
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 */
function erp_client_menu(){
	
	return array(
		"admin/config/erp/client"=>array(
			"title"=>"ERP Client",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_client_form"),
			"access arguments"=>array("administer clients"),
			"file"=>"erp_client.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"admin/config/erp/client/settings"=>array(
			"title"=>"Settings",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		)
	);
	
}

function erp_client_load($client_id){
	
}

/**
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_entity_info/7
 */
function erp_client_entity_info(){
	
	return array(
		"erp_client"=>array(
			"label"=>"ERP client",
			"label callback"=>"erp_client_label",
			"controller class"=>"ClientController",
			"base table"=>"erp_clients",
			"load hook"=>"erp_client_load",
			"uri callback"=>"erp_client_uri",
			"fieldable"=>true,
			"entity keys"=>array(
				"id"=>"id"
			),
			"bundles"=>array(
				"erp_client"=>array(
					"label"=>t("Client"),
					"admin"=>array(
						"path"=>"admin/config/erp/client",
						"access callback"=>array("administer clients")
					)
				)
			)
		)
	);
	
}