<?php

function erp_client_install(){
	
// 	$db = new ClientDb();
// 	try {
// 		$db->modify_tables();
// 	}
// 	catch(Exception $e){
// 		watchdog_exception("ClientDB", $e);
// 	}
	
}

function erp_client_uninstall(){
	
}

/**
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 */
function erp_client_permission(){
	
	return array(
		"administer clients"=>array(
			"title"=>t("Administer ERP Client"),
			"description"=>t("Administer erp clients")
		)
	);
	
}

/**
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 */
function erp_client_menu(){
	
	return array(
		"admin/config/erp/client"=>array(
			"title"=>"ERP Client",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_client_config_form"),
			"access arguments"=>array("administer erp clients"),
			"file"=>"erp_client.admin.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"admin/config/erp/client/settings"=>array(
			"title"=>"Settings",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"erp/client/add"=>array(
			"title"=>"Add Client",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_client_form"),
			"access arguments"=>array("administer erp clients"),
			"file"=>"erp_client.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"erp/client/%erp_client"=>array(
			"title"=>"View Client",
			"title callback"=>"erp_client_title_callback",
			"title arguments"=>array(2),
			"page callback"=>"erp_client_view",
			"page arguments"=>array(2),
			"access callback"=>"erp_access",
			"access arguments"=>array("administer erp clients",2),
			"file"=>"erp_client.pages.inc",
			"type"=>MENU_NORMAL_ITEM
		),
		"erp/client/%erp_client/view"=>array(
			"title"=>"View",
			"type"=>MENU_DEFAULT_LOCAL_TASK
		),
		"erp/client/%erp_client/edit"=>array(
			"title"=>"Edit",
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("erp_client_form",2),
			"access callback"=>"erp_access",
			"access arguments"=>array("administer erp clients",2),
			"file"=>"erp_client.pages.inc",
			"type"=>MENU_LOCAL_TASK
		)
	);
	
}

function erp_client_title_callback($client){
	
	return $client->name;
	
}

/**
 * 
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_theme/7
 */
function erp_client_theme($existing, $type, $theme, $path){
	
	return array(
		"erp_client_view"=>array(
			"variables"=>array(
				"client"=>null
			),
			"template"=>"erp-client-view"
		)
	);
	
}

function erp_client_load($client_id, $reset=false){
	
	$clients = erp_client_load_multiple(array($client_id), array(), $reset);
	return reset($clients);
	
}

function erp_client_load_multiple($client_ids = array(), $conditions = array(), $reset=false){
	
	return entity_load("erp_client", $client_ids, $conditions, $reset);
	
}

/**
 * @link http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_entity_info/7
 */
function erp_client_entity_info(){
	
	return array(
		"erp_client"=>array(
			"label"=>"ERP client",
			"label callback"=>"erp_client_label",
			"controller class"=>"ClientController",
			"base table"=>"erp_clients",
			"load hook"=>"erp_client_load",
			"uri callback"=>"erp_client_uri",
			"fieldable"=>true,
			"entity keys"=>array(
				"id"=>"id"
			),
			"bundles"=>array(
				"erp_client"=>array(
					"label"=>t("Client"),
					"admin"=>array(
						"path"=>"admin/config/erp/client",
						"access arguments"=>array("administer clients")
					)
				)
			)
		)
	);
	
}

function erp_client_field_extra_fields(){
	
	return array(
		"erp_client"=>array(
			"erp_client"=>array(
				"form"=>array(
					"name"=>array(
						"label"=>t("Name"),
						"description"=>t("Client name"),
						"weight"=>1
					),
					"desc"=>array(
						"label"=>t("Description"),
						"description"=>t("Client description"),
						"weight"=>2
					)
				),
				"display"=>array(
					"name"=>array(
						"label"=>t("Name"),
						"description"=>t("Client name"),
						"weight"=>1
					),
					"desc"=>array(
						"label"=>t("Description"),
						"description"=>t("Client description"),
						"weight"=>2
					)
				)
			)
		)
	);
	
}